dist: xenial
language: cpp
install: 
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install -y automake autoconf libtool make gettext lzip
  - sudo apt-get install -y mingw-w64 pkg-config wx-common subversion git
  - sudo chmod +x ./deps.sh
  - ./deps.sh
build:
  - sudo chmod +x ./build.sh
  - ./build.sh
